### ISSUE TITLE
IP address pool per APN

### ISSUE THREAD

**Issue by thakurajayL** [omec-project/ngic-rtc#100]
PGW should support multiple APNs and IP address pool per APN. This gives freedom to edge network  to do their own routing for the IP address of the  pool.

**Comment by thakurajayL** [comment]
@krsna1729 @ajamshed Can we plan this ? Not sure if this is already done in any other branch.

**Comment by ajamshed** [comment]
@thakurajayL,

I think there was some work done by Suresh in one of the private repositories on this. Let me check and see if the patch can be applied to the current code. Give me some time for this :).

**Comment by thakurajayL** [comment]
@ajamshed  Thanks !

**Comment by thakurajayL** [comment]
I will say address per UPF/SPGW-U instance. or APN... we should design in a way which kind of aligns with 5G :)

**Comment by RafalArciszewski** [comment]
the SPGW-U will have a slice of APN pool. This is planned in tmopl repo.
