### ISSUE TITLE
PGW should support hairPin traffic

### ISSUE THREAD

**Issue by thakurajayL** [omec-project/ngic-rtc#101]
PGW should have ability to loopback the traffic if traffic origination & destination are in the same s1-u interface. Example is 1 mobile accessing http APIs provided by other mobile.    Or lets say pinging from 1 mobile to other mobile.  DO we support it as of now ?

**Comment by RafalArciszewski** [comment]
no, the UE-to-UE packet will go out via SGi interface and come back via SGi interface if the SGi network allows this.

**Comment by thakurajayL** [comment]
Once packet leaves PGW on SGi interface, then it becomes dependent on the network devices on the SGi interface.
