### ISSUE TITLE
Static address allocation support by PDN GW

### ISSUE THREAD

**Issue by thakurajayL** [omec-project/ngic-rtc#109]
PDN GW should support static address allocation. This is done by 2 ways typically

1.  MME pulls the subscriber profile from HSS. This profile has the IP address assignment. This address is sent in Create Session Request towards PDN GW. PDN GW validates the address. If address validation is successful then received address is sent back to MME. 

2. PDN GW can have DHCP server.  Create Session Req/Rsp does not assign any address to the UE. This is because PCO indicates dhcp based address allocation. 
    Once UE is attached to network, then Client sends the DHCP request for the address assignment. PDN gw takes care of address assignment and sends back the assigned IP address to UE. 
    This has more work in the PDN GW..

**Comment by RafalArciszewski** [comment]
the first option is on a roadmap in tmopl repo

**Comment by thakurajayL** [comment]
Code is already pushed into the branch - central-cp-multi-upfs

**Comment by thakurajayL** [comment]
Fixed in central-cp-multi-upfs
