### ISSUE TITLE
DP kni interface config when processing traffic causes crash

### ISSUE THREAD

**Issue by krsna1729** [omec-project/ngic-rtc#14]
Capture the bug we discovered internally in the release notes, if it has not been fixed already.

Excerpt: 

_We tried to execute a couple of commands specific to S1Udev/SGIdev interface configurations with ngic-rtc (KNI mode). It turns that running commands such as changing MTU size (when ngic-rtc is running against il_trafficgen) triggers a crash. This is because the current code is not taking care of the race condition(s) that may arise when MTU size is being changed (rx/tx operations on the NIC are not paused, while ports are being configured)._

Close this issue if it has been fixed.

**Comment by krsna1729** [comment]
dp.log

```
CS and MB Requests Generator is started ....!!!


    Please wait for DP configured message ....!!!
Route entry ADDED in hash table ::
-----------     -------         --------        ------  ------
Destination     Gateway         Netmask         flags   Ifname
-----------     -------         --------        ------  ------
11.0.0.0         0.0.0.0        255.0.0.0       3       S1Udev
-----------     -------         --------        ------  ------
Route entry DELETED from hash table ::
-----------     -------         --------        ------  ------
Destination     Gateway         Netmask         flags   Ifname
-----------     -------         --------        ------  ------
11.0.0.0         0.0.0.0        255.0.0.0       3       S1Udev
-----------     -------         --------        ------  ------
Route entry ADDED in hash table ::
-----------     -------         --------        ------  ------
Destination     Gateway         Netmask         flags   Ifname
-----------     -------         --------        ------  ------
11.1.1.0         0.0.0.0        255.255.255.0   3       S1Udev
-----------     -------         --------        ------  ------


##NGCORE_SHRINK(RTC)
                  UPLINK                            ||                 DOWNLINK
IfMisPKTS    IfPKTS     UL-RX     UL-TX    UL-DFF   || IfMisPKTS    IfPKTS     DL-RX     DL-TX    DL-DFF
        0         3         0         0         0   ||         0         6         0         0         0

**************************
STATS ::
**************************
MAX_NUM_CS    : 50000
MAX_NUM_MB    : 50000
NUM_CS_SEND   : 50000
NUM_MB_SEND   : 50000
NUM_CS_FAILED : 0
NUM_MB_FAILED : 0
**************************


************ DP Configured successfully ************
        0         6         0         0         0   ||         0         9         0         0         0
        0   4089336   2093170   2093154        16   ||         0     96585     96698     96674        24
./run.sh: line 167: 247511 Segmentation fault      (core dumped) $APP_PATH/$APP $ARGS
```

Initialized KNI devs
```
sudo ./kni-SGIdevcfg.sh
SGIdev    Link encap:Ethernet  HWaddr 3c:fd:fe:b6:00:e9
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

SGIdev    Link encap:Ethernet  HWaddr 3c:fd:fe:b6:00:e9
          inet addr:13.1.1.93  Bcast:13.1.1.255  Mask:255.255.255.0
          inet6 addr: fe80::3efd:feff:feb6:e9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

intel-lab@ngic-skx:~/ngic-rtc/kni_ifcfg⟫ sudo ./kni-S1Udevcfg.sh
S1Udev    Link encap:Ethernet  HWaddr 3c:fd:fe:b6:00:e8
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

S1Udev    Link encap:Ethernet  HWaddr 3c:fd:fe:b6:00:e8
          inet addr:11.1.1.93  Bcast:11.1.1.255  Mask:255.255.255.0
          inet6 addr: fe80::3efd:feff:feb6:e8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
Output of `ip link`.
```
intel-lab@ngic-skx:~/ngic-rtc/kni_ifcfg⟫ sudo ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid a4bf014b886a state UP mode DEFAULT group default qlen 1000
    link/ether a4:bf:01:4b:88:6a brd ff:ff:ff:ff:ff:ff
3: eno2: <BROADCAST,MULTICAST> mtu 1200 qdisc mq portid a4bf014b886b state DOWN mode DEFAULT group default qlen 1000
    link/ether a4:bf:01:4b:88:6b brd ff:ff:ff:ff:ff:ff
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:37:b9:e8:92 brd ff:ff:ff:ff:ff:ff
47: S1Udev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:b6:00:e8 brd ff:ff:ff:ff:ff:ff
48: SGIdev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:b6:00:e9 brd ff:ff:ff:ff:ff:ff
```
Started il_trafficgen, followed by change in mtu size @ S1Udev interface
```
intel-lab@ngic-skx:~/ngic-rtc/kni_ifcfg⟫ sudo ip link set mtu 1200 S1Udev
RTNETLINK answers: Timer expired
```
At this point, DP crashes. Check DP log below.
```
2 intel-lab@ngic-skx:~/ngic-rtc/kni_ifcfg⟫ sudo ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq portid a4bf014b886a state UP mode DEFAULT group default qlen 1000
    link/ether a4:bf:01:4b:88:6a brd ff:ff:ff:ff:ff:ff
3: eno2: <BROADCAST,MULTICAST> mtu 1200 qdisc mq portid a4bf014b886b state DOWN mode DEFAULT group default qlen 1000
    link/ether a4:bf:01:4b:88:6b brd ff:ff:ff:ff:ff:ff
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:37:b9:e8:92 brd ff:ff:ff:ff:ff:ff
```

**Comment by ajamshed** [comment]
Also,

The kni callback function for ``kni_config_network_interface()`` needs some cleanup. A new udp socket is created and ``fd_array[port_id]`` is reset every time interface is brought up/down https://github.com/omec-project/ngic-rtc/blob/d65e86595d03c4786ce9e6380f2e0d64c6f1db33/dp/kni_pkt_handler.c#L365. The ``fd_array[port_id]`` I believe is used by the DP to communicate with the kernel _e.g._ ARP messages. This will lead to unreliable/lossy communication between ngic-rtc and the kernel.

**Comment by vishal-sangale** [comment]
Sai,

We again verify the case, where we changing the MTU size(when ngic-rtc is in running state), but Not found the issue where dp is crash.
But still if your facing that issue, please let us know the steps where we can re-produce it.


DP Logs:  
root@sprint-dp3-f1-4:/home/rest_test/ngic-rtc/kni_ifcfg# ip link show
	
774: S1Udev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a1:38:a8 brd ff:ff:ff:ff:ff:ff
775: SGIdev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a1:38:a9 brd ff:ff:ff:ff:ff:ff

root@sprint-dp3-f1-4:/home/rest_test/ngic-rtc/kni_ifcfg# ip link set mtu 1200 S1Udev

root@sprint-dp3-f1-4:/home/rest_test/ngic-rtc/kni_ifcfg# ip link show
774: S1Udev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1200 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a1:38:a8 brd ff:ff:ff:ff:ff:ff
775: SGIdev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a1:38:a9 brd ff:ff:ff:ff:ff:ff

root@sprint-dp3-f1-4:/home/rest_test/ngic-rtc/kni_ifcfg# ip link set mtu 9000 SGIdev

root@sprint-dp3-f1-4:/home/rest_test/ngic-rtc/kni_ifcfg# ip link show
774: S1Udev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1200 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a1:38:a8 brd ff:ff:ff:ff:ff:ff
6: ens786f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop portid 3cfdfea13332 state DOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a1:33:32 brd ff:ff:ff:ff:ff:ff
775: SGIdev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 3c:fd:fe:a1:38:a9 brd ff:ff:ff:ff:ff:ff

**Comment by krsna1729** [comment]
@vishal-sangale 

The race we saw was UL does RX on S1U & TX on SGI, and DL does RX on SGI & TX on S1U. Now when we change any link parameter of say S1U, it will be handled by UL core after pipeline run. But DL core has no idea of this and tries to TX on S1U.

This was tested with il_trafficgen and ideally *should* not depend on the traffic generator used. Can you please point me to the portion of the code where the synchronization happens among UL/DL cores or with the master core.

**Comment by ajamshed** [comment]
@vishal-sangale,

I just verified that the above mentioned issue still exists. We previously verified it wlth ``il_trafficgen``, and I have tested it again with ``ng40``. You can try changing the mtu size of either ``S1Udev`` or ``SGIDev`` while the generator is sending packets on the dataplane path. As Sai mentioned above, we need to pause both worker cores (UL + DL) before issuing a change in mtu size.
