### ISSUE TITLE
Support FQDN along with IPs

### ISSUE THREAD

**Issue by krsna1729** [omec-project/ngic-rtc#2]
This is essential in dynamic environments where depending on 

- [x] https://github.com/omec-project/ngic-rtc/blob/master/cp/main.c#L134-L138
- [x] https://github.com/omec-project/ngic-rtc/blob/master/interface/interface.c#L989-L996

Have retry logic that would do X tries with Y seconds of sleep before giving up on name resolution and exit

**Comment by lbertz02** [comment]
Is the change on interface.c only?  I am not sure that L134-L138 are an issue as it appears to be more about who is calling that function correct?

**Comment by krsna1729** [comment]
@lbertz02 since we parse IPs in two places i mentioned both
1. from commadline in main.c
2. from interface.cfg in interface.c

unfortunately we do not reuse the function nor do we know why we use multi-line macros for this.
¯\_(ツ)_/¯
