### ISSUE TITLE
Simplify DP config file

### ISSUE THREAD

**Issue by amitinfo2k** [omec-project/ngic-rtc#22]
Currently in DP configuration  (dp_config.cfg) user needs to specify  PCI ID and MAC Address where, there is chance of typo error. Instead, we can use the Port index (DPDK port bind order) and using DPDK API get the MAC address which will make configuration simple.

**Comment by krsna1729** [comment]
Welcome @amitinfo2k ! Thanks for the suggestion.

To be specific, the DP code does not use PCI ID passed in, it is only referenced by run script to populate the EAL `whitelist` argument. And yes it seems redundant to require the user to set both.

Relying only on the Port index may not be a good idea in orchestrated environments, where we aim to be fully automated with zero device handling by the application developer/user. With only port index user would have to know the device information apriori which port index is going to be S1U and which one is SGI. So we should atleast keep the MAC address option, to be able to use representors interface in Linux mirroing the DPDK bound devices could be used to figure out which interface is S1U vs SGI. Follow more here https://github.com/intel/sriov-cni/issues/37

Also there is #1 open to discuss streamlining the all the configuration passed itself, to avoid redundancies like above. Do take a look and provide feedback!
