### ISSUE TITLE
NIC checksum offloading for vdevs?

### ISSUE THREAD

**Issue by ajamshed** [omec-project/ngic-rtc#29]
We are currently relying on NIC-based checksum verification in `init.c`:

https://github.com/omec-project/ngic-rtc/blob/d65e86595d03c4786ce9e6380f2e0d64c6f1db33/dp/init.c#L88-L99.

Does this cover checksum offloading for vdevs as well (e.g. `virtio` & `af_packet` devices)? This needs to be investigated.

Otherwise we need to have a pure SW-based fallback for RX-based checksum verification.

**Comment by krsna1729** [comment]
@omec-project/ngic-maintainers @omec-project/docs
