### ISSUE TITLE
Test and apply the original AVX i40e fix patch

### ISSUE THREAD

**Issue by krsna1729** [omec-project/ngic-rtc#34]
Today we carry DPDK patch for rearm issue [here ](https://github.com/omec-project/ngic-rtc/blob/d65e86595d03c4786ce9e6380f2e0d64c6f1db33/patches/avx_not_suported.patch)

Lets see if the original patch to address the issue works with 18.02 and carry that instead
http://patches.dpdk.org/patch/43451/

cc @ajamshed

**Comment by ajamshed** [comment]
I just verified that this patch works on my testbed. My testbed specs:

Intel(R) Xeon(R) Platinum 8170 CPU @ 2.10GHz (dual-socket)
Intel XL710 dual port adapter (40 GbE QSFP+)

**Comment by krsna1729** [comment]
@ajamshed Can you send a PR to update the patch used?
