### ISSUE TITLE
PGWU: Not able to launch, failed to create Rx/Tx rings.

### ISSUE THREAD

**Issue by vishal-sangale** [omec-project/ngic-rtc#47]
PGWU failed to launch due to RX/TX ring creation is failed. 

RING: Cannot reserve memory
EAL: Error - exiting with code: 1
  Cause: Cannot create RX ring 0

**Comment by mkcet** [comment]
We have faced this same issue as well. Is there any work around for this?

**Comment by mkcet** [comment]
By the way SGWU is running properly. 
And both running SGWU and failed PGWU run.sh logs are attached.

[omec-pgwu.txt](https://github.com/omec-project/ngic-rtc/files/3525628/omec-pgwu.txt)
[omec-sgwu.txt](https://github.com/omec-project/ngic-rtc/files/3525626/omec-sgwu.txt)

**Comment by krsna1729** [comment]
To make some notes - 

- You are using AF_PACKET instead of KNI (because of some other error you saw)
- Seems like the processing stage initialization is duplicated in case of pgwu?

```
DP Port initialization completed.
ARP-ICMP Core on:               3
CP-DP IFACE Core on:            4
SPNS DNS Core on:               4
STATS-Timer Core on:            3

API: Netlink socket event reader thread created successfully...!!!
Uplink Core on:                 5
Downlink Core on:               6
ARP-ICMP Core on:               3
CP-DP IFACE Core on:            4
SPNS DNS Core on:               4
STATS-Timer Core on:            3
RING: Cannot reserve memory
EAL: Error - exiting with code: 1
  Cause: Cannot create RX ring 0
```

**Comment by mkcet** [comment]
I tried KNI and after running ./kni-S1Udevcfg.sh, we get "SIOCSIFFLAGS: Operation not permitted". And when we check to run.sh log, we see below error.

i40e_alloc_rx_queue_mbufs(): Failed to allocate mbuf for RX
i40evf_dev_rx_queue_start(): Failed to allocate RX queue mbuf
i40evf_start_queues(): Fail to start queue 0
i40evf_dev_start(): enable queues failed
i40evf_add_del_all_mac_addr(): fail to execute command OP_DEL_ETHER_ADDRESS

And the output of lshw -c network output related to S1U and SGI is below. These are disabled and i don't know why seen as Wireless interface.
  *-network:0 DISABLED
       description: Wireless interface
       physical id: 1
       logical name: SGIdev
       serial: fa:16:3e:e0:e8:7c
       capabilities: ethernet physical wireless
       configuration: broadcast=yes ip=172.17.250.153 multicast=yes
  *-network:1 DISABLED
       description: Wireless interface
       physical id: 2
       logical name: S1Udev
       serial: fa:16:3e:e4:75:6c
       capabilities: ethernet physical wireless
       configuration: broadcast=yes ip=10.154.11.153 multicast=yes

**Comment by amitinfo2k** [comment]
Raised PR addressing this issue of error creating Rx/Tx rings in case of PGWU config.
