### ISSUE TITLE
DP should convey its S1U IP to CP on start up

### ISSUE THREAD

**Issue by krsna1729** [omec-project/ngic-rtc#56]
Instead of user providing S1U IP of DP in the CP commandline arguments, the DP can send a message to CP with this information. This will reduce the number of things to know upfront for CP.

**Comment by ajamshed** [comment]
Yes. This may work. Probably after `init_s11()` is called?

**Comment by lbertz02** [comment]
FYI - In Sx this is part of the association establishment.  If you feel there is more data missing on startup you can look at the TS 29.244 spec for association establishment - it is what 3GPP thinks they need between DP and CP on startup
