### ISSUE TITLE
Move -DNGCORE_SHRINK into DP Makefile

### ISSUE THREAD

**Issue by krsna1729** [omec-project/ngic-rtc#63]
Any reason to have `CFLAGS += -DNGCORE_SHRINK` in `config/ng-core_cfg.mk` ? Can we move it into `dp/Makefile`

**Comment by ajamshed** [comment]
Actually I don't even think the macro is needed any more (default is `NGCORE_SHRINK`). The old pipeline model should be deprecated by now. Maybe we should remove it from the code totally???

**Comment by krsna1729** [comment]
@ajamshed even better. @suresh-marikkannu @somnathchakrabarti any thoughts?
