### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by krsna1729** [omec-project/ngic-rtc#7]
Add Dockerfile and Makefile targets to build S/PGW-C/U images.

Depends-on: #6 to stay free of duplication of installation steps

**Comment by lbertz02** [comment]
1. Change name of request to 'Add Dockerfile and Makefile targets'
2. A relation is noted for #6 but is the intent of this enhancement to coexist with existing scripts?

**Comment by krsna1729** [comment]
@lbertz02 
1. updated in the corresponding PR instead of here
2. Ideally want to get rid of current install.sh

**Comment by krsna1729** [comment]
#15 merged
