### ISSUE TITLE
Add kubernetes manifests

### ISSUE THREAD

**Issue by krsna1729** [omec-project/ngic-rtc#8]
Add manifests under `deploy/k8s` folder that will help bring up each of the S/PGW-C/U components in this repo

**Comment by lbertz02** [comment]
There is no deployment diagram and this is a VNF.  How will this look and kubernetes and should that be in a deploy folder?

**Comment by krsna1729** [comment]
@lbertz02 what do you want to see in a deployment diagram. I would need more context for "and this is a VNF". Where according to you should it be?
