### ISSUE TITLE
ngic_dataplane dropping >90% of transmitted and received packets from il_trafficgen

### ISSUE THREAD

**Issue by Ravi-t** [omec-project/ngic-rtc#92]
Hello,

I am testing for high traffic using ngic_dataplane and il_trafficgen as explained in il_trafficgen.
I am having 2 servers, 40 core 256 GB RAM with two 10GE NICs each.

I can see that il_trafficgen is working well and generating the required traffic towards ngic_dataplane but ngic_dataplane is dropping lots of packets as evident from stats below.

Please help me that how can I avoid suck huge > 90% packet drop.

**./build/ngic_dataplane -l 0,2,4,8,10,12,14 -n 4 --file-prefix dp -w 0000:81:00.0 -w 0000:81:00.1 --socket-mem 10240,10240 -- --s1u_ip 11.7.1.93 --s1u_mask 255.255.255.0 --s1u_mac a0:36:9f:85:88:c8 --sgi_ip 13.7.1.93 --sgi_mask 255.255.255.0 --sgi_mac a0:36:9f:85:88:ca --num_workers 1 --log 0 --numa 1 --gtpu_seqnb_in 0 --gtpu_seqnb_out 0 --spgw_cfg 03 --ul_iface S1Udev --dl_iface SGIdev --kni_portmask 03 --cdr_path ./cdr --master_cdr ./cdr/master.csv**

**ngic_dataplane stats are pasted below:**

************ DP Configured successfully ************
                  UPLINK                            ||                 DOWNLINK
IfMisPKTS    IfPKTS     UL-RX     UL-TX    UL-DFF   || IfMisPKTS    IfPKTS     DL-RX     DL-TX    DL-DFF 
        0         0         0         0         0   ||         0         0         0         0         0 
        0         0         0         0         0   ||         0         0         0         0         0 
        0         0         0         0         0   ||         0         0         0         0         0 
        0         0         0         0         0   ||         0         0         0         0         0 
        0   8978164   8978657    280000   8698657   ||         0         0         0         0         0 
        0  28959585  28960069    890000  28070069   ||         0         0         0         0         0 
        0  48938459  48938944   1500000  47438944   ||         0         0         0         0         0 
        0  68918624  68919178   2110000  66809178   ||         0  17119314    520001    520000         1 
        0  88897347  88897891   2720000  86177891   ||         0  37104761   1130001   1130000         1 
        0 108874554 108875101   3330000 105545101   ||         0  57087979   1740003   1740000         3 
        0 128853664 128854213   3940000 124914213   ||         0  77073746   2350000   2350000         0 
        0 148832771 148833313   4550000 144283313   ||         0  97059008   2960000   2960000         0 
        0 168812332 168812879   5160000 163652879   ||         0 117045465   3570002   3570000         2 
        0 188791040 188791589   5770000 183021589   ||         0 137030540   4180003   4180000         3 
        0 208770612 208771159   6380000 202391159   ||         0 157016224   4790000   4790000         0 
        0 228751517 228752063   6990000 221762063   ||         0 177003593   5400002   5400000         2 
        0 248730336 248730956   7600000 241130956   ||         0 196988458   6010000   6010000         0 
        0 268709408 268709954   8210000 260499954   ||         0 216973803   6620004   6620000         4 
        0 288689862 288690432   8814347 279876085   ||         0 236961280   7230002   7230000         2 
        0 308669131 308669684   9420000 299249684   ||         0 256946672   7840000   7840000         0 
##NGCORE_SHRINK(RTC)
                  UPLINK                            ||                 DOWNLINK
IfMisPKTS    IfPKTS     UL-RX     UL-TX    UL-DFF   || IfMisPKTS    IfPKTS     DL-RX     DL-TX    DL-DFF 
        0 328646720 328647268  10030000 318617268   ||         0 276929856   8450002   8450000         2 
        0 348625792 348626348  10640000 337986348   ||         0 296915520   9060002   9060000         2 
        0 368604672 368605207  11250000 357355207   ||         0 316900140   9670000   9670000         0 
        0 388581758 388582306  11860000 376722306   ||         0 336883531  10280000  10280000         0 
        0 399575712 399575712  12200000 387375712   ||         0 356868536  10890003  10890000         3 

**Stats at il_trafficgen**

********** Uplink Table **************
S1U_PktTx (Total Pkts) >>   AS_PktRx (Total Pkts)
  399575712                    12200000

********** Downlink Table **************
S1u_PktRx (Total Pkts) <<   AS_PktTx (Total Pkts) 
  12200000                   799450912 

UL Loss = S1u_PktTx - AS_PktRx = 387375712(pkts); 96.95(%)
DL Loss = AS_PktTx - S1u_PktRx = 787250912(pkts); 98.47(%)

**Comment by ajamshed** [comment]
@Ravi-t,

`il_trafficgen` only works when you run `ngic-rtc` in `SIMU_CP` mode (i.e. all sessions need to simulated/created within `ngic-rtc`). If you want to run `ngic_dataplane` against `il_trafficgen`, then please make sure that you have `SIMU_CP` as well as `STATIC_ARP` enabled in `dp/Makefile`.

Also, please make sure that the MAC addresses in `config/static_arp.cfg` match with `il_trafficgen`'s `user_input.cfg` fields. The fields in `config/simu_cp.cfg` should also match the fields set in `user_input.cfg`.

**Comment by Ravi-t** [comment]
Dear Ajam,
Thanks a lot for your recommendations.

But I already made sure that SIMU_CP and STATIC_ARP are enabled in Makefile and MAC addresses are also matching in all cfg files before I started testing. I have attached all the cfg files (OMEC NGIC.zip) and Makefile for your reference. 

I am not seeing any error being reported by ngic dataplane while running in debug mode. Only in stats I can see that UL-DFF is non-zero and around 97% of total packets sent are dropped. Only 3% packets are processed successfully by app. The IfMisPKTS  for both uplink and downlink is 0.
Please let me know how to proceed.

grep Huge /proc/meminfo 
AnonHugePages:     57344 kB
HugePages_Total:      48
HugePages_Free:       18
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB


The output of cpu layout is as below.
======================================================================
Core and Socket Information (as reported by '/sys/devices/system/cpu')
======================================================================

cores =  [0, 1, 2, 3, 4, 8, 9, 10, 11, 12]
sockets =  [0, 1]

        Socket 0        Socket 1       
        --------        --------       
Core 0  [0, 20]         [1, 21]        
Core 1  [2, 22]         [3, 23]        
Core 2  [4, 24]         [5, 25]        
Core 3  [6, 26]         [7, 27]        
Core 4  [8, 28]         [9, 29]        
Core 8  [10, 30]        [11, 31]       
Core 9  [12, 32]        [13, 33]       
Core 10 [14, 34]        [15, 35]       
Core 11 [16, 36]        [17, 37]       
Core 12 [18, 38]        [19, 39]   

./build/ngic_dataplane -l 7-11 -n 4 --socket-mem 16000,16000 --file-prefix dp -w 0000:81:00.0 -w 0000:81:00.1 -- --s1u_ip 11.7.1.93 --s1u_mask 255.255.255.0 --s1u_mac a0:36:9f:85:88:c8 --sgi_ip 13.7.1.93 --sgi_mask 255.255.255.0 --sgi_mac a0:36:9f:85:88:ca --num_workers 1 --log 0 --numa 1 --gtpu_seqnb_in 0 --gtpu_seqnb_out 0 --spgw_cfg 03 --ul_iface S1Udev --dl_iface SGIdev --kni_portmask 03 --cdr_path ./cdr --master_cdr ./cdr/master.csv




[OMEC NGIC.zip](https://github.com/omec-project/ngic-rtc/files/3991407/OMEC.NGIC.zip)

**Comment by ajamshed** [comment]
Apologies for the delayed response. Can you please try re-running with less number of flows to begin with? Maybe with 100 subscribers (`flows=100` argument in `user_input.cfg` file as well as the `MAX_UE_SESS=100` argument in `simu_cp.cfg` file).

When one runs dp in `SIMU_CP` mode, it normally takes time to build sessions, and dp prints an acknowledgement that all simulated sessions have been created. I don't see that output in your log (you should probably wait for a few seconds on dp before you run ``il_trafficgen``.

**Comment by Ravi-t** [comment]
Thanks Ajam.
I would run again as recommended by you and let you know if I still face issues.

**Comment by Ravi-t** [comment]
Thanks Ajam...It started working.

**Comment by qzhang90** [comment]
Hi @Ravi-t , I am also trying to run il_trafficgen against nigc-rtc data plane. Do I need to start ngic-rtc control plane(i.e. execute run.sh under ngic-rtc/cp)? 
Thanks!

**Comment by Ravi-t** [comment]
Hi @qzhang90 

Control-plane is not needed to be started if you are using SIMU_CP mode, you can enable that through Makefile.

Regards

**Comment by qzhang90** [comment]
Thanks @Ravi-t . I followed the steps below, but was not successful. Can you please advise?
1. Enabled both `CFLAGS += -DSIMU_CP` and `CFLAGS += -DSTATIC_ARP`in `ngic-rtc/dp/Makefile`, and then built the dataplane by `make`
2. Started the dataplane by `./run.sh` under `ngic-rtc/dp`. The output of the dataplane is attached as `dataplane-output.txt`
3. Went to 'il_trafficgen/pktgen' and ran `./il_nperf.sh -g`. (The output is attached as output1.png)
4. Went to 'il_trafficgen/pktgen' and ran `./il_nperf.sh -r`. (The output is attached as output2.png)
5. From the prompt of step 3, ran `start 0`

After this, as shown in output3.png, I can only see the data being transmitted, but nothing else on either the receiver side or the dataplane side.

[Attachments.zip](https://github.com/omec-project/ngic-rtc/files/5817308/Attachments.zip)

**Comment by qzhang90** [comment]
@Ravi-t @ajamshed do we need to configure `sdf_rules.cfg`, `pcc_rules.cfg`, and `adc_rules.cfg` to run dataplane with a simulated controlplane? Thanks!

**Comment by Ravi-t** [comment]
@qzhang90 
No there is no need to configure such rules unless your test case needs them.
Before pumping data from il_nperf, please make sure that you sessions are established by simulated CP.
Only pump data after you see below logs

    Please wait for DP configured message ....!!!

```
**************************
STATS ::
**************************
MAX_NUM_CS    : 100
MAX_NUM_MB    : 100
NUM_CS_SEND   : 100
NUM_MB_SEND   : 100
NUM_CS_FAILED : 0
NUM_MB_FAILED : 0
**************************


************ DP Configured successfully ************
```

**Comment by qzhang90** [comment]
Thanks @Ravi-t ! Regarding to the other configurations, were you able to successfully run the dataplane with il_trafficgen by using the ones in `OMEC NGIC.zip` you attached?
