### ISSUE TITLE
Unable to route data packets to Application function

### ISSUE THREAD

**Issue by hrkgarg** [omec-project/ngic-rtc#93]
Hi,

I am trying to attach a UE into NGIC SPGW setup. 
Attach is successful. However, when I try to run data for the UE, then my application-function is unable to receive the packets from UE

Case 1 : (With Static ARP)

In this case, dataplane is showing data getting received and also getting forwarded. But nothing on the application function. I tried running the same on same machine as well as different machine. But nothing seems to be working. Attached are the logs.

[Issue-1.zip](https://github.com/omec-project/ngic-rtc/files/4026029/Issue-1.zip)

Case 2 : (With KNI config)

Same issue is present here as well. No data packet is visible.
[Issue-2.zip](https://github.com/omec-project/ngic-rtc/files/4026077/Issue-2.zip)

Configurations : 
[config.zip](https://github.com/omec-project/ngic-rtc/files/4026078/config.zip)
[kni_ifcfg.zip](https://github.com/omec-project/ngic-rtc/files/4026079/kni_ifcfg.zip)

So basic issue/query is that I want to know how to receive the packets on Application-function which is not using DPDK on the same or different VM.

Many thanks for the help.

**Comment by hrkgarg** [comment]
Attached are the traces for KNI config. 
[Issue-2.zip](https://github.com/omec-project/ngic-rtc/files/4026053/Issue-2.zip)

Configurations : 
[config.zip](https://github.com/omec-project/ngic-rtc/files/4026067/config.zip)
[kni_ifcfg.zip](https://github.com/omec-project/ngic-rtc/files/4026068/kni_ifcfg.zip)



[kni_ifcfg.zip](https://github.com/omec-project/ngic-rtc/files/4026064/kni_ifcfg.zip)

**Comment by ajamshed** [comment]
@hrkgarg,

Apologies for the delayed response. Let's try to fix case 1 first. Can you please share the contents of `static_arp.cfg` file? Also can you run `tcpdump` on the application server side. Are you not getting kind of traffic there?

**Comment by hrkgarg** [comment]
@ajamshed 

All the config files are already attached in config.zip including static_config.cfg
kni-config scripts are present in kni_ifcfg.zip

tcpdump is not showing any packets being received. Maybe because we are using DPDK. 
The pcap traces (already present in Issue1.zip have been generated by dataplane and is showing that it is forwarding the packets towards Application-function.

**Comment by ajamshed** [comment]
@hrkgarg,

Apologies for missing `config.zip` and `static_config.cfg` files earlier. They both seem okay. Can you please verify whether `S1Udev` and `SGIdev` are being assigned the correct IP addresses even for case 1 (`Machine-config.txt` shows that IP addresses are not being set). I am suspecting that the application server is trying to send ARP requests to SPGWU, but the ARP replies are not being returned.

**Comment by hrkgarg** [comment]
Hi @ajamshed 

Correct. The IPs are not assigned in Case-1 because as per your docs, there is no need to add IPs in case of static-arp case. So I didn't run the kni scripts to plumb the IP.

Only in second case, where I am running the using kni-config, I ran these scripts.

Is there any thing that I missed here ?

**Comment by ajamshed** [comment]
I am suspecting that ARP is not getting resolved between the application server and the SGi side. Did you put static ARP entries on the application server side as well? Can you try running the KNI scripts even for Case 1? We may have to update the README if it starts working.
