### ISSUE TITLE
DP not coming up on a VM with Huge pages of size 2M

### ISSUE THREAD

**Issue by Ravi-t** [omec-project/ngic-rtc#94]
I tested DP on a physical server with Hugepages of size 1G and it worked fine. But now I am trying to replicate my setup on a VM which only supports Huge pages of size 2M.
But its not coming up, even though my VM has 64 GB RAM. I tried other sample DPDK applications and they work fine, only OMEC DP and CP are not coming up. 

```
grep Huge /proc/meminfo 
AnonHugePages:     10240 kB
HugePages_Total:    9000
HugePages_Free:     8984
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

```
dp]# ./run.sh 
Setting up Control and Data Plane NUMA memory
-l 1-6 -n 1 
	--socket-mem 4096,4096 
	--file-prefix dp -w 0000:13:00.0 -w 0000:1b:00.0 
	-- 
	--s1u_ip 11.7.1.93 
	--s1u_mask 255.255.255.0 
	--s1u_mac a0:36:9f:85:88:c8 
	--sgi_ip 13.7.1.93 
	--sgi_mask 255.255.255.0 
	--sgi_mac a0:36:9f:85:88:ca 
	--num_workers 1 
	--log 0 
	--numa 1 
	--gtpu_seqnb_in 0 
	--gtpu_seqnb_out 0 
	--spgw_cfg 03 
	--ul_iface S1Udev 
	--dl_iface SGIdev 
	--kni_portmask 03 
	--cdr_path ./cdr 
	--master_cdr ./cdr/master.csv
EAL: Detected 8 lcore(s)
EAL: Multi-process socket /var/run/.dp_unix
EAL: Probing VFIO support...
EAL: Not enough memory available on socket 0! Requested: 4096MB, available: 32MB
EAL: FATAL: Cannot init memory

EAL: Cannot init memory

EAL: Error - exiting with code: 1
  Cause: Error with EAL initialization
```

```
./cpu_layout.py 
======================================================================
Core and Socket Information (as reported by '/sys/devices/system/cpu')
======================================================================

cores =  [0, 1, 2, 3]
sockets =  [0, 1]

       Socket 0    Socket 1   
       --------    --------   
Core 0 [0]         [4]        
Core 1 [1]         [5]        
Core 2 [2]         [6]        
Core 3 [3]         [7]   
```

```
./dpdk-devbind.py --status

Network devices using DPDK-compatible driver
============================================
0000:13:00.0 'VMXNET3 Ethernet Controller 07b0' drv=igb_uio unused=vmxnet3
0000:1b:00.0 'VMXNET3 Ethernet Controller 07b0' drv=igb_uio unused=vmxnet3

Network devices using kernel driver
===================================
0000:04:00.0 'VMXNET3 Ethernet Controller 07b0' if=ens161 drv=vmxnet3 unused=igb_uio *Active*
0000:0b:00.0 'VMXNET3 Ethernet Controller 07b0' if=ens192 drv=vmxnet3 unused=igb_uio *Active*
0000:0c:00.0 'VMXNET3 Ethernet Controller 07b0' if=ens193 drv=vmxnet3 unused=igb_uio *Active*

```

```
Total VM memory = 64GB

              total        used        free      shared  buff/cache   available
Mem:       65807912      674828    64844460       54324      288624    64618940
Swap:      16515068           0    16515068
```



While compiling DP, I made sure that DHUGE_PAGE_16GB flag is commented.

**Comment by krsna1729** [comment]
`--socket-mem 4096,4096`

```
EAL: Not enough memory available on socket 0! Requested: 4096MB, available: 32MB
EAL: FATAL: Cannot init memory
```
Seems like there huge page allocation was not equal to both sockets?

**Comment by Ravi-t** [comment]
I disabled numa in config so that only numa0 is used but still getting the same error.

```
dp]# ./run.sh 
Setting up Control and Data Plane NUMA memory
-l 1-6 -n 1 
	--socket-mem 4096,0 
	--file-prefix dp -w 0000:13:00.0 -w 0000:1b:00.0 
	-- 
	--s1u_ip 11.7.1.93 
	--s1u_mask 255.255.255.0 
	--s1u_mac a0:36:9f:85:88:c8 
	--sgi_ip 13.7.1.93 
	--sgi_mask 255.255.255.0 
	--sgi_mac a0:36:9f:85:88:ca 
	--num_workers 1 
	--log 0 
	--numa 0 
	--gtpu_seqnb_in 0 
	--gtpu_seqnb_out 0 
	--spgw_cfg 03 
	--ul_iface S1Udev 
	--dl_iface SGIdev 
	--kni_portmask 03 
	--cdr_path ./cdr 
	--master_cdr ./cdr/master.csv
EAL: Detected 8 lcore(s)
EAL: Multi-process socket /var/run/.dp_unix
EAL: Probing VFIO support...
EAL: Not enough memory available on socket 0! Requested: 4096MB, available: 32MB
EAL: FATAL: Cannot init memory

EAL: Cannot init memory

EAL: Error - exiting with code: 1
  Cause: Error with EAL initialization
```

**Comment by krsna1729** [comment]
That 16 pages used (9000-8984) = 32MB and the error saying 32MB available is weird. Can you clean out any rte_map files under hugepage mount point and retry?

**Comment by Ravi-t** [comment]
I rebooted the server and started everything again, I also cleaned hugepages from /dev/hugepages but nothing helped.

After rebooting the server, my Huge pages were as shown below, I also tried playing with overcommit by making its value 0 and 9000 but nothing worked.
```
cd /sys/kernel/mm/hugepages/hugepages-2048kB
hugepages-2048kB]# for i in *; do echo -ne $i=;cat $i;done 
free_hugepages=9000
nr_hugepages=9000
nr_hugepages_mempolicy=9000
nr_overcommit_hugepages=9000
resv_hugepages=0
surplus_hugepages=0
```
 
Now, I started the dp again and got the same error. Basically, hugepages before starting dp were 9000, but after dp start fails and if I again check the hugepages, it shows that only 16 pages in total are available and free becomes 16.

```
dp]# ./run.sh 
Setting up Control and Data Plane NUMA memory
-l 1-6 -n 4 
	--socket-mem 4096,4096 
	--file-prefix dp -w 0000:13:00.0 -w 0000:1b:00.0 
	-- 
	--s1u_ip 11.7.1.93 
	--s1u_mask 255.255.255.0 
	--s1u_mac 00:50:56:aa:35:12 
	--sgi_ip 13.7.1.93 
	--sgi_mask 255.255.255.0 
	--sgi_mac 00:50:56:aa:04:d1 
	--num_workers 1 
	--log 0 
	--numa 0 
	--gtpu_seqnb_in 0 
	--gtpu_seqnb_out 0 
	--spgw_cfg 03 
	--ul_iface S1Udev 
	--dl_iface SGIdev 
	--kni_portmask 03 
	--cdr_path ./cdr 
	--master_cdr ./cdr/master.csv
EAL: Detected 8 lcore(s)
EAL: Multi-process socket /var/run/.dp_unix
EAL: Probing VFIO support...
EAL: Not enough memory available on socket 0! Requested: 4096MB, available: 32MB
EAL: FATAL: Cannot init memory

EAL: Cannot init memory
```

EAL: Error - exiting with code: 1
  Cause: Error with EAL initialization


```
cd /sys/kernel/mm/hugepages/hugepages-2048kB/
[hugepages-2048kB]# for i in *; do echo -ne $i=;cat $i;done 
free_hugepages=0
nr_hugepages=16
nr_hugepages_mempolicy=16
nr_overcommit_hugepages=9000
resv_hugepages=0
surplus_hugepages=0
```

**Comment by Ravi-t** [comment]
As the error was not making much sense, so I recreated the VM and it started working.
